//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportNetwork.WebFormsApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportNetwork.WebFormsApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на автобусы.
        /// </summary>
        internal static string ControlForm_InitializeComponent_автобусы {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_автобусы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная форма.
        /// </summary>
        internal static string ControlForm_InitializeComponent_Главная_форма {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_Главная_форма", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string ControlForm_InitializeComponent_Название {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_Название", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на продажа билетов.
        /// </summary>
        internal static string ControlForm_InitializeComponent_продажа_билетов {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_продажа_билетов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на путевые листы.
        /// </summary>
        internal static string ControlForm_InitializeComponent_путевые_листы {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_путевые_листы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на рейсы.
        /// </summary>
        internal static string ControlForm_InitializeComponent_рейсы {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_рейсы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сотрудники.
        /// </summary>
        internal static string ControlForm_InitializeComponent_сотрудники {
            get {
                return ResourceManager.GetString("ControlForm_InitializeComponent_сотрудники", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели неверные пароль или логин.
        /// </summary>
        internal static string LoginForm_enterButton_Click_Error_Message {
            get {
                return ResourceManager.GetString("LoginForm_enterButton_Click_Error_Message", resourceCulture);
            }
        }
    }
}
